version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
